### ISSUE TITLE
spotify playlist issue

### ISSUE THREAD

**Issue by 100TapZ** [DeltaCoderr/KarmaBot#102]
spotify playlist but it only play 1 music instead of the entire playlist

**Comment by DeltaCoderr** [comment]
Yeah, I don't think the current version of `discord-player` that the bot uses does not support playing the entire playlist from spotify.

**Comment by Sadboiako420** [comment]
Should i update the `discord-player` to fix this?

**Comment by DeltaCoderr** [comment]
I guess so, But the latest versions also does have Breaking Changes. And I would confirm it first if it actually works then update it.
