### ISSUE TITLE
[Djs-v14] Complete rewrite

### ISSUE THREAD

**Issue by DeltaCoderr** [DeltaCoderr/KarmaBot#114]
All the new changes will be done in this [branch](https://github.com/DeltaCoderr/KarmaBot/tree/Rewrite-djsv14)

Since Karma uses v12 for now, I'm thinking to switch to slash commands so it would be beneficial for users to use the commands more efficiently.

Any PR'S are welcome.

**Comment by Yash-271120** [comment]
@DeltaCoderr Hi can you assign this issue to me? :)

**Comment by DevilzzNikhil** [comment]
can i also be assigned 
@DeltaCoderr

**Comment by DeltaCoderr** [comment]
Sure @DevilzzNikhil, Just make sure to take your time and decide on what part to work on first

@Yash-271120 you too.

**Comment by Yash-271120** [comment]
@DeltaCoderr I had question that are you planning to switch all the commands to slash commands? If so I can start with changes in Loader.js and then take up the `NSFW` commands(they seem easy :) )

**Comment by DeltaCoderr** [comment]
> @DeltaCoderr I had question that are you planning to switch all the commands to slash commands? If so I can start with changes in Loader.js and then take up the `NSFW` commands(they seem easy :) )

Yes!

**Comment by Yash-271120** [comment]
Yes assign me back. Thanx.

**Comment by kyrea** [comment]
Could you please assign me to this.

**Comment by DeltaCoderr** [comment]
Done! @kyrea

**Comment by Zerapium** [comment]
yo assign me
