### ISSUE TITLE
One more thing i am tryin to add a kick comma

### ISSUE THREAD

**Issue by dog1cool** [DeltaCoderr/KarmaBot#19]

**Comment by dog1cool** [comment]
the issue is it wont work no error no anything

**Comment by dog1cool** [comment]
U used the command test and copy it to kick.js /
const Discord = require('discord.js');
const config = require('../../configs/config.json');


module.exports = {
    config: {
        name: 'kick',
        description: 'kick user',
        aliases: ["k"],
        usage: '',
        accessableby: "",
    },
    run: async (client, message) => {
            const target = message.mentions.users.first();
        if(target){
            const memberTarget = message.guild.members.cache.get(target.id);
            memberTarget.kick();
            message.channel.send("User has been kicked");
        }else{
            message.channel.send(`You coudn't kick that member!`);
        }
    }
}

**Comment by DeltaCoderr** [comment]
could you join the support server (Discord) so we can talk and discuss there?
