### ISSUE TITLE
Need moderation and automod

### ISSUE THREAD

**Issue by ChillNotTaken** [DeltaCoderr/KarmaBot#20]
Can you make like good moderation commands,lock channel and unlock channel and serverlock and server unlock & CAN U MAKE LIKE AUTO REDDIT POSTING? & finally some basic automod if u can? Other then that epic bot 😍🤩

**Comment by DeltaCoderr** [comment]
#2  (that issue is for moderation commands)
well, I'm busy with classes and other work, Though we did start making moderation commands in Dev branch
It'll take some time to complete 👍🏻
