### ISSUE TITLE
cant be online i used heroku host 

### ISSUE THREAD

**Issue by ZEROO202** [DeltaCoderr/KarmaBot#25]

**Comment by ZEROO202** [comment]
i need host

**Comment by DeltaCoderr** [comment]
Use repl, I recommend using it instead of Heroku.

**Comment by DeltaCoderr** [comment]
Check the README file, It has a button "Run on Repl"

**Comment by DeltaCoderr** [comment]
If you have any more questions, feel free to join the support server 
Link is in the readme.
