### ISSUE TITLE
[NSFW] Need new NSFW API

### ISSUE THREAD

**Issue by DeltaCoderr** [DeltaCoderr/KarmaBot#26]
As the API Karma Bot was using for NSFW was Nekos.life, and It seems that API returns Images of Minors which are against Discord TOS
So, I've had to remove them forcefully as it could be a trouble If I kept using them
If you have any new NSFW API's that aren't against Discord TOS. Feel free to Drop a Comment about it!

**Comment by Madnesssik** [comment]
Checkout this: https://www.nekos.fun/apidoc.html

**Comment by DeltaCoderr** [comment]
Ok so, I talked with top.gg mods and seems like one of their Community Managers do have an API which is trusted/safe 
https://shiro.gg/api/endpoints
I guess, I'll implement this API in the commands.

**Comment by DeltaCoderr** [comment]
Okay, successfully implemented the new API in the new commands, Should work fine without any issues now. 👍🏻
