### ISSUE TITLE
How to get mongoDB URL

### ISSUE THREAD

**Issue by proudparrot2** [DeltaCoderr/KarmaBot#38]
Hi,
I am relatively new to coding, and I wanted to ask - how do you get a mongoDB URL? I tried looking at https://github.com/DeltaCoderr/KarmaBot/wiki but it redirected me back to the main KarmaBot page. Can someone please explain, or show me a good page that can help me?

Thanks!

**Comment by DeltaCoderr** [comment]
Hello! I already made a gist tutorial on how you can get the mongodb url which can be found [Here](https://gist.github.com/DeltaCoderr/0de27e6088822302dcb27db1827d64c1) I'll try making a wiki page with exact steps  once I get time to do

**Comment by proudparrot2** [comment]
Thanks for your help! I thought someone would just say "Look it up on Google!" Which is what I did, but none of them were helpful.

**Comment by DeltaCoderr** [comment]
Glad to see you got it 👍🏻
