### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vanna-code** [DeltaCoderr/KarmaBot#43]
handlers\command.js:8
            client.commands.set(pull.config.name, pull); 
                                            ^

TypeError: Cannot read property 'name' of undefined

**Comment by DeltaCoderr** [comment]
You probably forgot to include config.name in one of your command files.

**Comment by DeltaCoderr** [comment]
Closing this, Feel free to open an Issue if you got more questions.
