### ISSUE TITLE
Index.js

### ISSUE THREAD

**Issue by lakshya14066** [DeltaCoderr/KarmaBot#44]
Sir it is asking index.js file to be made to run

**Comment by notkyoyo** [comment]
Could you please elaborate?

**Comment by notkyoyo** [comment]
Following [this](https://github.com/DeltaCoderr/KarmaBot#bot-setup--) steps should help you to launch the bot.

**Comment by lakshya14066** [comment]
I m using dan bot hosting to make bot

**Comment by notkyoyo** [comment]
I don't know what that is, could you please write the error here? Also, please use the code blocks.

**Comment by DeltaCoderr** [comment]
Closing this, Feel free to make an issue again If you have a question.
