### ISSUE TITLE
Problem with setChatbotchannel command.

### ISSUE THREAD

**Issue by UnDeadLolomat** [DeltaCoderr/KarmaBot#46]
Hey, so i aslo had a chatbot api and stuff, thats why i searched for a way to do it for multiple servers, and now i found yours, which i then modified. Its just telling me now, that its not a valid channel or doesnt has enough perms. That is not the case tho, cuz it has admin perms and its a normal text channel. Modified code : [here](https://sourceb.in/5n0oIlVXR3) The error with command and valid channel + perms [here](https://ibb.co/MGq98PN)

**Comment by DeltaCoderr** [comment]
Try logging the error.

**Comment by UnDeadLolomat** [comment]
Thanks, problem fixed! Was just an easy error lol. I forgot to change one emote.verified to emojis.success ... 
I am dumb, thank u for ur help!
