### ISSUE TITLE
the api might need an update 

### ISSUE THREAD

**Issue by fluffy29922** [DeltaCoderr/KarmaBot#56]
Some commands in anime and image effects aren't working

**Comment by DeltaCoderr** [comment]
Which ones to be specific?

**Comment by fluffy29922** [comment]
Current ones i know of that arent working are fact and trash

**Comment by DeltaCoderr** [comment]
I'll take a look, The `trash` one probably isn't working because of an API Issue
And the `anime-facts` package is updated so

**Comment by DeltaCoderr** [comment]
Updated both of these commands 👍🏻 
You can take a look
