### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ChillNotTaken** [DeltaCoderr/KarmaBot#69]
Make help command using buttons use slider npm

**Comment by ChillNotTaken** [comment]
https://www.npmjs.com/package/discord-slider

**Comment by DeltaCoderr** [comment]
Might try it out, I'm refactoring the whole code at the moment. So it'll take some time

**Comment by DeltaCoderr** [comment]
Oh well, I refactored the bot but decided to go with a Dynamic Help command, and keep it in the normal way as it is (embed) 
And I don't wanna install a package just for a command which just adds some pages which display all the commands.
Thanks for the suggestion though
