### ISSUE TITLE
[4.0.0] - Discord.js v13 Refactor  

### ISSUE THREAD

**Issue by DeltaCoderr** [DeltaCoderr/KarmaBot#89]
Since Discord.js v13 is out. I'll probably update the bot to v13 as well, as it brings in the implementation of Buttons and Slash Commands.

I made a separate branch for Djs-v13 so all the PRS will go in that branch and once approved, will be merged in the branch with the release of the 4.0.0 version 

* The branch is [Here](https://github.com/DeltaCoderr/KarmaBot/tree/Djs-v13/) 
* Updating from V12 to V13 guide can be found [Here](https://discordjs.guide/additional-info/changes-in-v13.html#before-you-start)

**Comment by sujalgoel** [comment]
ok!

**Comment by SwarajBaral** [comment]
Hey @DeltaCoderr can I chip in to contribute in this as well ?

**Comment by DeltaCoderr** [comment]
Hey @SwarajBaral, Do you mind joining the [Discord](https://discord.gg/xab3SPNe). It would be convenient to talk with us there and discuss what changes we are going to implement.

**Comment by SwarajBaral** [comment]
Thanks @DeltaCoderr, I have joined the server.

**Comment by Lebyy** [comment]
On it!

**Comment by guddu75** [comment]
Hey @DeltaCoderr  I just learned how to make bot using discordJS v13 . Can i contribute ?

**Comment by DeltaCoderr** [comment]
Update : The Djs-v13 branch didn't work out well, So I decided to shift on a completely new handler. It's a bit better compared to the last one and easier to understand with the Slash Commands Integration and has a Error Handler. 

* New changes will be done in this [branch](https://github.com/DeltaCoderr/KarmaBot/tree/test)
