### ISSUE TITLE
Request to add a github action

### ISSUE THREAD

**Issue by Jassi10000** [DeltaCoderr/KarmaBot#93]
Feature request :
KarmaBot is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by DeltaCoderr** [comment]
Sure, go ahead and make a PR at the dev branch! 

I would love to see a Github Action welcoming the contributors on their every Issue and PR.

**Comment by Jassi10000** [comment]
Can you please tell what do you mean by dev branch 
Does it mean to create a new branch by the name of dev  ?

**Comment by Jassi10000** [comment]
@DeltaCoderr Do I have make the changes of this too in develop branch ??

**Comment by DeltaCoderr** [comment]
Yep.
