### ISSUE TITLE
Request to add CODE_OF_CONDUCT to the repo

### ISSUE THREAD

**Issue by Jassi10000** [DeltaCoderr/KarmaBot#94]
@DeltaCoderr 
I have opened this issue in reference to the issue no #93 

For writing a meaningful github action , i need a CODE_OF_CONDUCT.md file which is currently lacking from the repository 
Can you please assign this issue to me so that I can add the CODE_OF_CONDUCT.md file first and then more further to write a meaningful github action for the repository

**Comment by Jassi10000** [comment]
@DeltaCoderr 
Can you please assign me this , so that after adding the CODE_OF_CONDUCT.md , I can more forward to adding the gh action for this repo

**Comment by DeltaCoderr** [comment]
Alright, go ahead Make sure you make the PR in [develop](https://github.com/DeltaCoderr/KarmaBot/tree/develop) branch So I can merge it.
